# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BianDianSuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biandiansuo', models.CharField(max_length=10, verbose_name='变电所名称')),
                ('voltage_level', models.CharField(choices=[('35kV', '35kV'), ('110kV', '110kV'), ('220kV', '220kV')], max_length=10, verbose_name='电压等级')),
                ('touyunriqi', models.DateField(verbose_name='投运日期')),
            ],
            options={
                'verbose_name_plural': '变电所',
                'verbose_name': '变电所',
            },
        ),
        migrations.CreateModel(
            name='CaoZuoPiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leibie', models.CharField(choices=[('体内操作票', '体内操作票'), ('体外操作票', '体外操作票')], max_length=5, verbose_name='操作票类别')),
                ('bianhao', models.CharField(max_length=20, verbose_name='操作票编号')),
                ('caozuoneirong', models.CharField(max_length=100, verbose_name='操作内容')),
                ('falinren', models.CharField(max_length=10, verbose_name='发令人')),
                ('falinshijian', models.DateTimeField(verbose_name='发令时间')),
                ('kaishishijian', models.DateTimeField(verbose_name='开始时间')),
                ('jiesushijian', models.DateTimeField(verbose_name='结束时间')),
                ('nipiaoren', models.CharField(max_length=10, verbose_name='拟票人')),
                ('shenpiaoren', models.CharField(max_length=10, verbose_name='审票人')),
                ('caozuoren', models.CharField(max_length=10, verbose_name='操作人')),
                ('jianhuren', models.CharField(max_length=10, verbose_name='监护人')),
                ('zhibanfuzeren', models.CharField(max_length=10, verbose_name='值班负责人（值长）')),
                ('biandiansuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdgqpt.BianDianSuo', verbose_name='变电所')),
            ],
            options={
                'verbose_name_plural': '操作票',
                'verbose_name': '操作票',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_No', models.CharField(max_length=8, verbose_name='工号')),
                ('full_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phone_number', models.CharField(max_length=11, verbose_name='联系电话')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '人员信息',
                'verbose_name': '人员信息',
            },
        ),
        migrations.CreateModel(
            name='YunWeiZhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yunweizhan', models.CharField(max_length=10, verbose_name='运维站名称')),
            ],
            options={
                'verbose_name_plural': '运维站',
                'verbose_name': '运维站',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='yunweizhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdgqpt.YunWeiZhan', verbose_name='所属运维站'),
        ),
        migrations.AddField(
            model_name='biandiansuo',
            name='yunweizhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdgqpt.YunWeiZhan', verbose_name='所属运维站'),
        ),
    ]
