# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdgqpt', '0003_auto_20160823_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caozuopiao',
            name='caozuoneirong',
            field=models.CharField(max_length=100, null=True, verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='caozuoren',
            field=models.CharField(max_length=10, null=True, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='falinren',
            field=models.CharField(max_length=10, null=True, verbose_name='发令人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='falinshijian',
            field=models.DateTimeField(null=True, verbose_name='发令时间'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='jianhuren',
            field=models.CharField(max_length=10, null=True, verbose_name='监护人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='jiesushijian',
            field=models.DateTimeField(null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='kaishishijian',
            field=models.DateTimeField(null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='nipiaoren',
            field=models.CharField(max_length=10, null=True, verbose_name='拟票人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='shenpiaoren',
            field=models.CharField(max_length=10, null=True, verbose_name='审票人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='zhibanfuzeren',
            field=models.CharField(max_length=10, null=True, verbose_name='值班负责人（值长）'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='zhuangtai',
            field=models.CharField(choices=[('已执行', '已执行'), ('未执行', '未执行'), ('不执行', '不执行')], default='未执行', max_length=5, verbose_name='状态'),
        ),
    ]
