# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdgqpt', '0004_auto_20160824_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caozuopiao',
            name='zhuangtai',
            field=models.CharField(choices=[('', '-----------'), ('已执行', '已执行'), ('未执行', '未执行'), ('不执行', '不执行')], max_length=5, verbose_name='状态'),
        ),
    ]
