# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdgqpt', '0006_auto_20160902_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caozuopiao',
            name='caozuoneirong',
            field=models.CharField(max_length=100, verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='caozuoren',
            field=models.CharField(max_length=10, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='falinren',
            field=models.CharField(max_length=10, verbose_name='发令人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='falinshijian',
            field=models.DateTimeField(verbose_name='发令时间'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='jianhuren',
            field=models.CharField(max_length=10, verbose_name='监护人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='jiesushijian',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='kaishishijian',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='nipiaoren',
            field=models.CharField(max_length=10, verbose_name='拟票人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='shenpiaoren',
            field=models.CharField(max_length=10, verbose_name='审票人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='zhibanfuzeren',
            field=models.CharField(max_length=10, verbose_name='值班负责人（值长）'),
        ),
    ]
