# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdgqpt', '0007_auto_20160904_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caozuopiao',
            options={'ordering': ['-id'], 'verbose_name': '操作票', 'verbose_name_plural': '操作票'},
        ),
        migrations.AddField(
            model_name='caozuopiao',
            name='bushu',
            field=models.PositiveIntegerField(default=100, verbose_name='步数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='caozuoren',
            field=models.CharField(blank=True, max_length=10, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='falinren',
            field=models.CharField(blank=True, max_length=10, verbose_name='发令人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='falinshijian',
            field=models.DateTimeField(blank=True, verbose_name='发令时间'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='jianhuren',
            field=models.CharField(blank=True, max_length=10, verbose_name='监护人'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='jiesushijian',
            field=models.DateTimeField(blank=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='kaishishijian',
            field=models.DateTimeField(blank=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='zhibanfuzeren',
            field=models.CharField(blank=True, max_length=10, verbose_name='值班负责人（值长）'),
        ),
    ]
