# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdgqpt', '0008_auto_20160908_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caozuopiao',
            name='falinren',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='发令人'),
        ),
    ]
