# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdgqpt', '0009_auto_20160908_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caozuopiao',
            name='falinshijian',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发令时间'),
        ),
    ]
