# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdgqpt', '0010_auto_20160908_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caozuopiao',
            name='falinren',
            field=models.CharField(blank=True, default=1, max_length=10, verbose_name='发令人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='jiesushijian',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='kaishishijian',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
