# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 05:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdgqpt', '0011_auto_20160908_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caozuopiao',
            name='biandiansuo',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='yunweizhan', chained_model_field='yunweizhan', on_delete=django.db.models.deletion.CASCADE, to='bdgqpt.BianDianSuo', verbose_name='变电所'),
        ),
    ]
