# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdgqpt', '0013_caozuopiao_beizhu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biandiansuo',
            name='yunweizhan',
        ),
        migrations.AlterModelOptions(
            name='caozuopiao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='beizhu',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='biandiansuo',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='bianhao',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='bushu',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='caozuoneirong',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='caozuoren',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='falinren',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='falinshijian',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='jianhuren',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='jiesushijian',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='kaishishijian',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='leibie',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='shenpiaoren',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='zhibanfuzeren',
        ),
        migrations.RemoveField(
            model_name='caozuopiao',
            name='zhuangtai',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='yunweizhan',
        ),
        migrations.AlterField(
            model_name='caozuopiao',
            name='nipiaoren',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ID_No',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.DeleteModel(
            name='BianDianSuo',
        ),
        migrations.DeleteModel(
            name='YunWeiZhan',
        ),
    ]
